name: Build Env

on:
 workflow_dispatch:

env:
  UBUNTU_VERSION: 22.04
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  cpu-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          # Undeclared SHA tags with latest commit from master branch
          - {latest: "false", python: "3.10", pytorch: "2.2.1"}
          - {latest: "true", sha: "abc1234", python: "3.10", pytorch: "2.2.1"}
    steps:
      -
        name: Env Setter
        run: |
          echo "PACKAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      -
        name: Set tags
        run: |
          img_path="ghcr.io/${{ env.PACKAGE_NAME }}"
          if [[ -z '${{ matrix.build.sha }}' ]]; then
              COMFYUI_SHA="$(curl -fsSL "https://api.github.com/repos/comfyanonymous/ComfyUI/commits/master" | jq -r '.sha[0:7]')"
          else
              COMFYUI_SHA="${{ matrix.build.sha }}"
          fi
          [ -z "$COMFYUI_SHA" ] && { echo "Error: COMFYUI_SHA is empty. Exiting script." >&2; exit 1; }
          
          base_tag="newbase-${{ matrix.build.pytorch }}-py${{ matrix.build.python }}-cpu-${{ env.UBUNTU_VERSION }}"
          sha_tag="${base_tag}-${COMFYUI_SHA}"
          TAGS="${img_path}:${sha_tag}"
          if [[ ${{ matrix.build.latest }} == "true" ]]; then
              echo "Marking latest"
              TAGS+=", ${img_path}:latest-cpu, ${img_path}:latest-cpu-jupyter"
          fi
